language: node_js
node_js:
  - "8"

install:
  - yarn global add @angular/cli
  - cd logic
  - yarn
  - cd ..
  
script:
  - cd frontend
  - yarn
  - ng build --prod
  - cd ../backend
  - yarn
  - yarn build
  - cd ..
  - mkdir ./backend/dist/public
  - mv ./frontend/dist ./backend/dist/public
deploy:
  provider: heroku
  app: shashki
  api_key:
    secure: XCEbYZ8iiQQ+UAoTOMlpOvHjh2tcCArCgcA049erE5eoNghEqQkYI6VVQo2PotKamS2N1c$
