language: node_js
node_js:
  - "8"

install:
  - yarn global add @angular/cli
  - cd logic
  - yarn
  
script:
  - cd ./frontend
  - yarn
  - ng build --prod
  - cd ../backend
  - yarn
  - yarn build
  - cd ..
  - mkdir ./backend/dist/public
  - mv ./frontend/dist ./backend/dist/public
