language: node_js
node_js:
  - "8"

install:
  - yarn global add @angular/cli
  - cd logic
  - yarn
  - cd ..
  
script:
  - cd frontend
  - yarn
  - ng build --prod
  - cd ../backend
  - yarn
  - yarn build
  - cd ..
  - cp -R ./backend/dist ./src
  - mkdir ./src/public
  - mv ./frontend/dist ./src/public
  - rm -rf ./frontend
  - rm -rf ./backend
  - rm -rf ./logic
deploy:
  provider: heroku
  app: shashki
  api_key:
    secure: XCEbYZ8iiQQ+UAoTOMlpOvHjh2tcCArCgcA049erE5eoNghEqQkYI6VVQo2PotKamS2N1c$
